![](https://www.r-project.org/Rlogo.png)

____________________________________________________________________________________
This tutorial is the second part of a series. If you've never programmed before, I recommend checking out the "[First Steps](https://www.kaggle.com/rtatman/getting-started-in-r-first-steps/)" part of the tutorial.

In this part of the tutorial, we'll:

* read data into R
* look at the data we've read in
* remove unwanted rows

____________________________________________________________________________________


### Learning goals:

By the end of this tutorial, you will be able to do the following things. (Don't worry if you don't know what all these things are yet; we'll get there together!)

* [Be familiar with basic concepts: functions, variables, data types and vectors](https://www.kaggle.com/rtatman/getting-started-in-r-first-steps/)
* [Load data into R](https://www.kaggle.com/rtatman/getting-started-in-r-load-data-into-r)
* [Summerize your data](https://www.kaggle.com/rtatman/getting-started-in-r-summarize-data)
* [Graph data](https://www.kaggle.com/rtatman/getting-started-in-r-graphing-data/)

______

### Your turn!

Throughout this tutorial, you'll have lots of opportunities to practice what you've just learned. Look for the phrase "your turn!" to find these exercises.

## Reading data into R

When you read data into R, you need to tell it two things. The first is what type of data structure the data is in. The second is where to find the data.

> Data structure: A specfic way of organizing data to store it. There are lots of different types of data structures that you will learn about, including lists and trees. Vectors, which we talked about in the "First Steps" part of the tutorial, are a specific data structure.

For this tutorial, we're going to use the data_frame data structure (also called a tibble). If you're curious, you can find more information on these [here](https://cran.r-project.org/web/packages/tibble/vignettes/tibble.html). However, this data structure isn't one that comes with base R. To use this data structure, we're going to need to use  a package.

In [28]:
# this line will read in the "tidyverse" package. An R package is a collection
# of special functions (and sometimes data). Before you use can use the functions in a
# package, though, you need to tell R that you want it to use that package using the
# library() function.

library(tidyverse)

Alright, now that we've read in the package we need, we're ready to read in data. We can do this using the read_csv() function (which was in the package we just read in--if you try to use this function without loading the package using library() first, you'll get an error!).

Let's read  in our file. This file is a .csv file. "csv" stands for "comma separated values". You can save any spreadsheet at a .csv file, and that will make it easier to read and analyze later: many file types that you can save spreadsheets as can only be read by one specific program. A .csv can be read by pretty much any program.

For this tutorial, we'll be using a dataset of ratings of different chocolate bars. You can learn more about this dataset by clicking on the plus sign (+) next to "input files" at the top of the page.

In [29]:
# Read our data into R. The argument here is a file path. The ".." means "look at the 
# folder above this one", "input" is a specific folder, "chocolate-bar-ratings" is
# a folder wihtin the "input" folder, and and "flavors_of_cacao.csv" is 
# the specific file we're reading from inside that file.

chocolateData <- read_csv("../input/chocolate-bar-ratings/flavors_of_cacao.csv")

# some of our column names have spaces in them. This line changes the column names to 
# versions without spaces, which let's us talk about the columns by their names.
names(chocolateData) <- make.names(names(chocolateData), unique=TRUE)

Rows: 1795 Columns: 9
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (6): Company
(Maker-if known), Specific Bean Origin
or Bar Name, Cocoa
...
dbl (3): REF, Review
Date, Rating

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [30]:
# Your turn!

# To give you practice reading in files, I've added a second dataset to this notebook
# as well. This dataset is in the following place: ../input/food-choices/food_coded.csv

# read in your dataset and save it as a variable called "foodPreferences"
foodPreferences <- read_csv("../input/food-choices/food_coded.csv")

New names:
• `comfort_food_reasons_coded` -> `comfort_food_reasons_coded...10`
• `comfort_food_reasons_coded` -> `comfort_food_reasons_coded...12`
Rows: 125 Columns: 61
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (14): GPA, comfort_food, comfort_food_reasons, diet_current, eating_chan...
dbl (47): Gender, breakfast, calories_chicken, calories_day, calories_scone,...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

## Look at the data we've read in

Congrats, you've gotten some data into R! Now we want to make sure that it all read in correctly, and get an idea of what's in our data file.

In [31]:
# the head() function reads just the first few lines of a file. 
head(chocolateData)

# the tail() function reads in the just the last few lines of a file. 
# we can also give both functions a specific number of lines to read.
# This line will read in the last three lines of "chocolateData".
tail(chocolateData, 3)

  Company...Maker.if.known. Specific.Bean.Origin.or.Bar.Name REF  Review.Date
1 A. Morin                  Agua Grande                      1876 2016
2 A. Morin                  Kpime                            1676 2015
3 A. Morin                  Atsane                           1676 2015
4 A. Morin                  Akata                            1680 2015
5 A. Morin                  Quilla                           1704 2015
6 A. Morin                  Carenero                         1315 2014
  Cocoa.Percent Company.Location Rating Bean.Type Broad.Bean.Origin
1 63%           France           3.75             Sao Tome
2 70%           France           2.75             Togo
3 70%           France           3.00             Togo
4 70%           France           3.50             Togo
5 70%           France           3.50             Peru
6 70%           France           2.75   Criollo   Venezuela

  Company...Maker.if.known. Specific.Bean.Origin.or.Bar.Name REF Review.Date
1 Zotter                    Kerala State                     749 2011
2 Zotter                    Kerala State                     781 2011
3 Zotter                    Brazil, Mitzi Blue               486 2010
  Cocoa.Percent Company.Location Rating Bean.Type Broad.Bean.Origin
1 65%           Austria          3.50   Forastero India
2 62%           Austria          3.25             India
3 65%           Austria          3.00             Brazil

In [32]:
# Your turn!

# Get the first four lines of the foodPreferences dataframe you read in earlier
head(foodPreferences,4)

  GPA   Gender breakfast calories_chicken calories_day calories_scone coffee
1 2.4   2      1         430              NaN          315            1
2 3.654 1      1         610                3          420            2
3 3.3   1      1         720                4          420            2
4 3.2   1      1         430                3          420            2
  comfort_food                     comfort_food_reasons
1 none                             we dont have comfort
2 chocolate, chips, ice cream      Stress, bored, anger
3 frozen yogurt, pizza, fast food  stress, sadness
4 Pizza, Mac and cheese, ice cream Boredom
  comfort_food_reasons_coded...10 ⋯ soup sports thai_food tortilla_calories
1 9                               ⋯ 1    1      1         1165
2 1                               ⋯ 1    1      2          725
3 1                               ⋯ 1    2      5         1165
4 2                               ⋯ 1    2      5          725
  turkey_calories type_sports veggies_day vitamins waffle_calories
1 345             car racing  5           1        1315
2 690             Basketball  4           2         900
3 500             none        5           1         900
4 690             nan         3           1        1315
  weight
1 187
2 155
3 I'm not answering this.
4 Not sure, 240

You'll notice that the data_frame data structure has two dimensions, unlike the vectors we worked with in the "First Steps" part of the tutorial. But the secret is that both of these dimensions are actually vectors! This mean that we can access specific cells in our data_frame using the indexes of values we're interested in.

A quick refresher on how to acess data by its index:

In [33]:
# make a little example vector
a <- c(5,10,15)

# if you ask for something at an index, but don't say which one, you'll get everything
a[]

# if you ask for a value at a specific index, you'll only get only that value. In R,
# indexes start counting from 1 and go up. (So 3 is the third)
a[1]

[1]  5 10 15

[1] 5

Data_frames work the same way, but you need to specify both the row and column, with a comma between them.

> In R, if you ask for something from a two dimensional data structure, you'll always ask for the row first and the column second. So "dataObject[2,4]" means "give me whatever is in the 2nd row and 4th column of the data frame called 'dataObject'".
>
> One way to remember this is by thinking of "RC Cola". In the brand's name, "RC" stands for "Royal Crown"... but we can pretend it stands for "Row Column".

![](https://upload.wikimedia.org/wikipedia/commons/e/e9/Drink_Royal_Crown_Cola.jpg)

In [34]:
# get the contents in the cell in the sixth row and the forth column
chocolateData[6,4]

# get the contents of every cell in the 6th row (note that you still need the comma!)
chocolateData[6,]

# if you forget the coulmn, you'll get the 6th *column* instead of the 6th *row*
head(chocolateData[6])
# I've used "head" here because the column is very long and I don't want
# to fill up the screen by printing the whole thing out

  Review.Date
1 2014

  Company...Maker.if.known. Specific.Bean.Origin.or.Bar.Name REF  Review.Date
1 A. Morin                  Carenero                         1315 2014
  Cocoa.Percent Company.Location Rating Bean.Type Broad.Bean.Origin
1 70%           France           2.75   Criollo   Venezuela

  Company.Location
1 France
2 France
3 France
4 France
5 France
6 France

In [35]:
# Your turn!
# dataframe[row,column]
# Get the first row of your "foodPreferences" data_frame
foodPreferences[1,]
# Get the value from the cell in the 100th row and 4th column
foodPreferences[100,4]

  GPA Gender breakfast calories_chicken calories_day calories_scone coffee
1 2.4 2      1         430              NaN          315            1
  comfort_food comfort_food_reasons comfort_food_reasons_coded...10 ⋯ soup
1 none         we dont have comfort 9                               ⋯ 1
  sports thai_food tortilla_calories turkey_calories type_sports veggies_day
1 1      1         1165              345             car racing  5
  vitamins waffle_calories weight
1 1        1315            187

  calories_chicken
1 430

## Remove unwanted data

In addition to using indexes to get certain values, we can also use them to *remove* data we're not interested in. You can do this by putting a minus sign (-) in front of the index you don't want.

You may have noticed earlier that the first row of the "chocolateData" data_frame is the same as the column names. Let's remove it.

In [36]:
head(chocolateData)

  Company...Maker.if.known. Specific.Bean.Origin.or.Bar.Name REF  Review.Date
1 A. Morin                  Agua Grande                      1876 2016
2 A. Morin                  Kpime                            1676 2015
3 A. Morin                  Atsane                           1676 2015
4 A. Morin                  Akata                            1680 2015
5 A. Morin                  Quilla                           1704 2015
6 A. Morin                  Carenero                         1315 2014
  Cocoa.Percent Company.Location Rating Bean.Type Broad.Bean.Origin
1 63%           France           3.75             Sao Tome
2 70%           France           2.75             Togo
3 70%           France           3.00             Togo
4 70%           France           3.50             Togo
5 70%           France           3.50             Peru
6 70%           France           2.75   Criollo   Venezuela

In [37]:
# get all rows EXCEPT the first row and all columns of chocolateData
# By putting it back in the same variable, we're overwriting what was in 
# that variable before, so be careful with this!
chocolateData <- chocolateData[-1,] 

# make sure we removed the row we didn't want
head(chocolateData)

  Company...Maker.if.known. Specific.Bean.Origin.or.Bar.Name REF  Review.Date
1 A. Morin                  Kpime                            1676 2015
2 A. Morin                  Atsane                           1676 2015
3 A. Morin                  Akata                            1680 2015
4 A. Morin                  Quilla                           1704 2015
5 A. Morin                  Carenero                         1315 2014
6 A. Morin                  Cuba                             1315 2014
  Cocoa.Percent Company.Location Rating Bean.Type Broad.Bean.Origin
1 70%           France           2.75             Togo
2 70%           France           3.00             Togo
3 70%           France           3.50             Togo
4 70%           France           3.50             Peru
5 70%           France           2.75   Criollo   Venezuela
6 70%           France           3.50             Cuba

In [38]:
# Your turn!

# The 5th column in the "foodPreferences" dataset has a lot of values that aren't 
# numbers (nan means "not a number"). Can you remove the 5th column from the dataset?
foodPreferences<-foodPreferences[,-5]
foodPreferences

    GPA     Gender breakfast calories_chicken calories_scone coffee
1   2.4     2      1         430              315            1
2   3.654   1      1         610              420            2
3   3.3     1      1         720              420            2
4   3.2     1      1         430              420            2
5   3.5     1      1         720              420            2
6   2.25    1      1         610              980            2
7   3.8     2      1         610              420            2
8   3.3     1      1         720              420            1
9   3.3     1      1         430              420            1
10  3.3     1      1         430              315            2
11  3.5     1      1         610              980            2
12  3.904   1      1         720              420            2
13  3.4     2      1         430              420            2
14  3.6     1      1         610              420            2
15  3.1     2      1         610              420            2
16  nan     2      2         430              980            2
17  4       1      1         265              420            1
18  3.6     2      1         430              980            2
19  3.4     1      1         720              980            1
20  2.2     2      1         430              420            2
21  3.3     2      1         610              980            2
22  3.87    2      1         610              315            1
23  3.7     2      1         610              420            1
24  3.7     2      2         610              420            2
25  3.9     1      1         720              420            2
26  2.8     1      2         720              420            2
27  3.7     2      1         610              420            1
28  3       2      1         610              980            2
29  3.2     2      1         610              420            2
30  3.5     2      1         265              420            2
⋮   ⋮       ⋮      ⋮         ⋮                ⋮              ⋮
96  3.5     2      1         265              420            2
97  3.92    2      1         430              420            2
98  3.9     1      1         720              420            2
99  3.9     2      1         720              315            1
100 3.2     1      1         430              420            1
101 3.5     1      1         610              NaN            2
102 3.4     1      1         610              420            2
103 nan     1      1         610              420            2
104 3.7     1      1         610              420            2
105 Unknown 1      1         720              420            2
106 3       1      1         720              420            2
107 3       1      1         430              315            2
108 3.8     1      1         430              420            1
109 3.8     1      1         430              420            2
110 3.4     1      1         610              420            2
111 3.7     1      1         610              315            1
112 2.9     2      1         265              980            2
113 3.9     1      1         610              315            2
114 3.6     1      1         430              420            1
115 2.8     2      1         610              315            2
116 3.3     2      1         610              980            2
117 3.4     1      1         610              420            2
118 3.77    1      1         610              315            2
119 3.63    1      1         430              420            1
120 3.2     2      1         610              420            2
121 3.5     1      1         610              420            2
122 3       1      1         265              315            2
123 3.882   1      1         720              420            1
124 3       2      1         720              420            1
125 3.9     1      1         430              315            2
    comfort_food
1   none
2   chocolate, chips, ice cream
3   frozen yogurt, pizza, fast food
4   Pizza, Mac and cheese, ice cream
5   Ice cream, chocolate, chips
6   Candy, brownies and soda.
7   Chocolate, ice cream, french fries, pretzels
8   Ice cream, cheeseburgers, chips.
9   Donuts, ice cream, chips
10  Mac and cheese, chocolate, and pasta
11  Pasta, grandma homemade chocolate cake anything homemade
12  chocolate, pasta, soup, chips, popcorn
13  Cookies, popcorn, and chips
14  ice cream, cake, chocolate
15  Pizza, fruit, spaghetti, chicken and Potatoes
16  cookies, donuts, candy bars
17  Saltfish, Candy and Kit Kat
18  chips, cookies, ice cream
19  Chocolate, ice crea
20  pizza, wings, Chinese
21  Fast food, pizza, subs
22  chocolate, sweets, ice cream
23  burgers, chips, cookies
24  Chilli, soup, pot pie
25  Soup, pasta, brownies, cake
26  chocolate, ice cream/milkshake, cookies
27  Chips, ice cream, microwaveable foods
28  Chicken fingers, pizza
29  cookies, hot chocolate, beef jerky
30  Tomato soup, pizza, Fritos, Meatball sub, Dr. Pepper
⋮   ⋮
96  Doritos, mac and cheese, ice cream
97  Ice cream, cake, pop, pizza, and milkshakes.
98  Mac and Cheese, Pizza, Ice Cream and French Fries
99  Soup, pasta, cake
100 mac & cheese, frosted brownies, chicken nuggs
101 watermelon, grapes, ice cream
102 macaroni and cheese, stuffed peppers, hamburgers, french fries
103 Pizza, mashed potatoes, spaghetti
104 dark chocolate, terra chips, reese's cups(dark chocolate), and bread/crackers with cottage cheese
105 Chips, chocolate, ,mozzarella sticks
106 ice cream, chips, candy
107 Pizza, soda, chocolate brownie, chicken tikka masala and butter naan
108 Chocolate, Pasta, Cookies
109 Candy, salty snacks, toast
110 Mac in cheese, pizza, mozzarella sticks
111 Ice-cream, pizza, chocolate
112 snacks, chips,
113 Chocolate, Ice cream, pizza
114 ice cream, pizza, Chinese food
115 Burgers, indian and korean food
116 chocolate bar, ice cream, pretzels, potato chips and protein bars.
117 Ice cream, chocolate, pizza, cucumber
118 Noodle ( any kinds of noodle), Tuna sandwich, and Egg.
119 Chinese, chips, cake
120 chips, rice, chicken curry,
121 wine. mac and cheese, pizza, ice cream
122 Pizza / Wings / Cheesecake
123 rice, potato, seaweed soup
124 Mac n Cheese, Lasagna, Pizza
125 Chocolates, pizza, and Ritz.
    comfort_food_reasons
1   we dont have comfort
2   Stress, bored, anger
3   stress, sadness
4   Boredom
5   Stress, boredom, cravings
6   None, i don't eat comfort food. I just eat when i'm hungry.
7   stress, boredom
8   I eat comfort food when im stressed out from school(finals week), when I`m sad, or when i am dealing with personal family issues.
9   Boredom
10  Stress, anger and sadness
11  Boredom
12  sadness, stress, cold weather
13  Sadness, boredom, late night snack
14  stress,  boredom, special occasions
15  Friends, environment and boredom
16  boredom
17  Stress
18  I usually only eat comfort food when I'm bored, if i am doing something, i can go for hours without eating
19  Sadness, stress
20  boredom, sadness, hungry
21  happiness, satisfaction
22  Mostly boredom
23  sadness, depression
24  Stress and boredom
25  A long day, not feeling well, winter
26  boredom
27  Boredom, lazyniss
28  Boredom
29  survival, bored
30  Boredom, anger, drunkeness
⋮   ⋮
96  Boredom, hunger, snacking.
97  Happiness, sadness, celebration.
98  Boredom, anger and just being hungry in general.
99  Depression, comfort, accessibility
100 they are yummy, my boyfriend sometimes makes me sad, boredom
101 Sad, bored, excited
102 boredom, stress, mood swings
103 Anger, sadness
104 Anxiousness, watching TV I desire "comfort food"
105 Boredom, sadness, anxiety
106 Boredom, laziness, anger
107 Stress and sadness
108 I am always stressed out, and bored when I am in my apartment.
109 Stress, sadness, boredom
110 Stress, frustration, self-consciousness
111 Sadness and cravings
112 boredom
113 Sadness, happiness and boredom
114 Boredom and sadness
115 sadness, happiness and hunger
116 Stress, boredom and physical activity
117 loneliness, homework, boredom
118 When i'm  eating with my close friends/ Food smell or look good/ when I feel tired
119 Stress and boredom
120 Happiness, boredom, social event
121 boredom and sadness
122 Loneliness / Homesick / Sadness
123 sadness
124 happiness, they are some of my favorite foods
125 hormones, Premenstrual syndrome.
    comfort_food_reasons_coded...10 cook ⋯ soup sports thai_food
1   9                               2    ⋯ 1      1    1
2   1                               3    ⋯ 1      1    2
3   1                               1    ⋯ 1      2    5
4   2                               2    ⋯ 1      2    5
5   1                               1    ⋯ 1      1    4
6   4                               3    ⋯ 1      2    4
7   1                               2    ⋯ 1      1    5
8   1                               3    ⋯ 1      2    1
9   2                               3    ⋯ 2      2    5
10  1                               3    ⋯ 1      1    4
11  2                               1    ⋯ 1      1    2
12  3                               3    ⋯ 1      1    5
13  3                               5    ⋯ 2      1    3
14  1                               2    ⋯ 1      1    5
15  2                               3    ⋯ 1      1    4
16  2                               4    ⋯ 2      1    1
17  1                               3    ⋯ 1      2    1
18  2                               3    ⋯ 1      1    3
19  3                               3    ⋯ 2      2    1
20  2                               4    ⋯ 1    NaN    3
21  7                               5    ⋯ 1      1    1
22  2                               3    ⋯ 2      1    5
23  3                               5    ⋯ 1      1    4
24  1                               4    ⋯ 1      1    4
25  6                               1    ⋯ 2      2    4
26  2                               3    ⋯ 1      1    3
27  2                               3    ⋯ 2      1    2
28  2                               4    ⋯ 1      1    3
29  2                               2    ⋯ 1      2    1
30  2                               3    ⋯ 1      2    5
⋮   ⋮                               ⋮    ⋱ ⋮    ⋮      ⋮
96   2                                3  ⋯ 2      1    4
97   7                                2  ⋯ 1      2    3
98   2                                3  ⋯ 1      1    3
99   3                                4  ⋯ 1      1    5
100  3                                4  ⋯ 1      1    1
101  3                                3  ⋯ 1      1    5
102  2                                3  ⋯ 1      2    3
103  3                                2  ⋯ 1      2    2
104  8                                2  ⋯ 1      2    3
105  2                                4  ⋯ 2      2    5
106  2                                3  ⋯ 2      1    3
107 NA                                2  ⋯ 1      2    4
108 NA                                2  ⋯ 1      2    5
109 NA                                5  ⋯ 1      1    2
110 NA                                2  ⋯ 1      2    2
111 NA                                3  ⋯ 1      1    3
112 NA                                2  ⋯ 1      2    1
113 NA                                1  ⋯ 1      2    5
114 NA                                2  ⋯ 1      2    2
115 NA                                3  ⋯ 1      1    5
116 NA                                4  ⋯ 1      1    1
117 NA                                3  ⋯ 1      2    5
118 NA                                3  ⋯ 1      2    5
119 NA                                3  ⋯ 1      2    4
120 NA                                2  ⋯ 1      1    5
121 NA                                3  ⋯ 1      1    5
122 NA                                3  ⋯ 1    NaN    4
123 NA                                3  ⋯ 1      2    5
124 NA                                3  ⋯ 2      2    1
125 NA                              NaN  ⋯ 1      2    2
    tortilla_calories turkey_calories
1   1165              345
2    725              690
3   1165              500
4    725              690
5    940              500
6    940              345
7    940              690
8    725              500
9    725              345
10   580              345
11   940              345
12   940              500
13   940              500
14  1165              850
15   940              500
16   940              345
17   580              345
18   940              500
19  1165              690
20   940              345
21  1165              850
22   725              500
23   940              850
24   940              690
25   940              500
26  1165              690
27  1165              850
28  1165              500
29   940              500
30   580              500
⋮   ⋮                 ⋮
96  1165              690
97   725              500
98  1165              500
99  1165              690
100 1165              690
101  NaN              500
102 1165              500
103  940              500
104  725              345
105  940              690
106 1165              690
107  580              500
108 1165              690
109  580              345
110  940              690
111  580              690
112  725              345
113  725              500
114 1165              690
115  940              850
116 1165              690
117  725              345
118  725              690
119  940              345
120 1165              690
121  940              500
122  940              500
123  580              690
124  940              500
125  725              345
    type_sports                                                 veggies_day
1   car racing                                                  5
2   Basketball                                                  4
3   none                                                        5
4   nan                                                         3
5   Softball                                                    4
6   None.                                                       1
7   soccer                                                      4
8   none                                                        4
9   none                                                        3
10  field hockey                                                5
11  soccer                                                      5
12  Running                                                     5
13  Soccer and basketball                                       3
14  intramural volleyball                                       5
15  Hockey                                                      5
16  Hockey                                                      1
17  nan                                                         5
18  hockey                                                      4
19  dancing                                                     5
20  basketball                                                  2
21  Soccer                                                      3
22  Tennis                                                      2
23  tennis soccer gym                                           3
24  Gaelic Football                                             4
25  none                                                        4
26  Ice hockey                                                  3
27  Hockey                                                      3
28  Lacrosse                                                    5
29  nan                                                         2
30  nan                                                         4
⋮   ⋮                                                           ⋮
96  Wrestling                                                   4
97  Soccer                                                      2
98  Running                                                     5
99  Tennis                                                      4
100 softball                                                    5
101 Volleyball, Track                                           5
102 nan                                                         5
103 nan                                                         5
104 When I can, rarely though play pool, darts, and basketball. 5
105 None at the moment                                          5
106 volleyball                                                  2
107 None                                                        5
108 I used to play softball                                     4
109 Ice hockey                                                  5
110 None                                                        3
111 Volleyball                                                  3
112 nan                                                         3
113 nan                                                         3
114 None                                                        2
115 Tennis, Basketball                                          3
116 Hockey                                                      2
117 none                                                        5
118 No, I don't play sport.                                     3
119 None                                                        5
120 Soccer                                                      5
121 Softball                                                    5
122 basketball                                                  5
123 none                                                        4
124 nan                                                         3
125 nan                                                         4
    vitamins waffle_calories weight
1   1        1315            187
2   2         900            155
3   1         900            I'm not answering this.
4   1        1315            Not sure, 240
5   2         760            190
6   2        1315            190
7   1        1315            180
8   2        1315            137
9   2         760            180
10  1         900            125
11  2         900            116
12  1         900            110
13  2         575            264
14  2        1315            123
15  1         900            185
16  2        1315            180
17  1         760            145
18  2         900            170
19  1        1315            135
20  2         900            165
21  2        1315            175
22  2         900            195
23  1        1315            185
24  1        1315            185
25  2        1315            105
26  2         760            125
27  2        1315            160
28  1        1315            175
29  1        1315            180
30  1         760            167
⋮   ⋮        ⋮               ⋮
96  2        1315            184
97  1         900            210
98  2         760            155
99  1        1315            185
100 1         900            165
101 2         900            125
102 2        1315            160
103 1         900            135
104 1         760            130
105 1        1315            230
106 2        1315            125
107 2         760            130
108 2         900            165
109 2         760            128
110 1        1315            200
111 2         900            160
112 2        1315            170
113 2         900            129
114 2         900            170
115 2         760            138
116 2        1315            150
117 1        1315            170
118 1         760            113
119 2        1315            140
120 2        1315            185
121 1        1315            156
122 2        1315            180
123 2        1315            120
124 1        1315            135
125 2         575            135

Alright, now that we've read our data into R, checked that it looks alright and gotten rid of a row we didn't want, it's time to get down to doing some analysis. In the next section, we'll learn how to summerize our data and get into some basic statistics!

## Next step: [Summarize our data](https://www.kaggle.com/rtatman/getting-started-in-r-summarize-data/)